server:
  port: ${PORT:8082}
  servlet:
    context-path: /airNUR
spring:
  rabbitmq:
    virtual-host: hzgwkcsm
    host: toad.rmq.cloudamqp.com
    port: 5672
    username: hzgwkcsm
    password: feMUhIx0bxqeWN67wJEzjX4w3rUNBsSz

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://db-postgresql-nyc3-65217-do-user-15342906-0.c.db.ondigitalocean.com:25060/msproperty"
    username: doadmin
    password: AVNS_pdtP2atPlaIGHm23GUZ

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /
